version: '3'
services:
  comments_api:
    build: .
    ports:
      - ${PORT:-5500}:${PORT:-5500}
    volumes:
      - ./:/var/www/comments_api
    env_file:
      - ./.env
    environment:
      - PORT=5500
      - DATABASE_URL=postgres://chux:password@comments_api_db/comments_api
    container_name: comments_api
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - ${POSTGRES_HOST_PORT:-5433}:5432
    volumes:
      - ./db-backup/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_PORT=5433
      - POSTGRES_USER=chux
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comments_api
    container_name: comments_api_db
